version: '3'
services:
  payment-checkout:
    build: ./extras/docker
    ports:
     - "8080:8080"
     - "8000:8000"
     - "5005:5005"
    depends_on: 
     - "postgres"
    volumes:
     - .:/payment-exercise
     - mavendata:/maven-data/.m2/repository
    #tty: true
  postgres:
    image: "postgres:11"
    ports:
     - "5432:5432"
    volumes:
     - ./extras/database/create-db.sh:/docker-entrypoint-initdb.d/1-create-db.sh
     - ./extras/database/populate-tables.sql:/docker-entrypoint-initdb.d/2-populate-tables.sql
     - ./extras/database/clear-tables.sql:/docker-entrypoint-initdb.d/3-clear-tables.sql
    environment:
     - POSTGRES_PASSWORD=teste001
volumes:
  mavendata:
